config/routes.rb
Rails.application.routes.draw do

  scope module: :public do
    # root to: "homes#top"
    get "home", to:"homes#top"
    # User routes
    resource :users, only: [:index, :new, :create, :edit, :update]
    root  to: "user_sessions#new"
    post "login"    , to: "user_sessions#create"
    delete "logout" , to: "user_sessions#destroy"
    get "mypage"    , to: "users#show"
    get "myshift"   , to: "users#myshift"
    patch "reset"   , to: "users#reset"
    # Week routes
    get 'weeks/past', to: 'weeks#past'
    resources :weeks, only: [:index] do
      # Job routes
      get 'jobs/past', to: 'jobs#past'
      resources :jobs, only: [:index, :create, :edit, :update, :destroy]
    end
  end

  devise_for :admin ,controllers: {
    sessions: "admin/sessions",
    registrations: "admin/registrations"
    
  }

  namespace :admin do
    patch 'settings/toggle_visible', to: 'settings#toggle_visible'
    resources :users, only: [:index, :show, :edit, :update]
    get 'weeks/past', to: 'weeks#past'
    resources :weeks, only: [:index, :create, :destroy] do
      member do
        patch :is_created
      end
      get 'jobs/past', to: 'jobs#past'
      resources :jobs, only: [:index] do 
        collection do
          get :print
        end
      end
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user
  belongs_to :week

  validates :user_id, uniqueness: {scope: :week_id}
  validates :time1, :time2, :time3, :time4, :time5, :time6, :time7, :comment,
    presence: true, if: -> { [time1,time2,time3,time4,time5,time6,time7,comment].all?(&:blank?) }
  
  after_commit :broadcast_replace_job

  def split_time(str)
    return [str] if str.nil? || str.empty?
    if str.scan(/[-ー~～]/).size == 1
      str.split(/[-ー~～]/).map(&:strip)
    else
      [str]
    end
  end

  def parsed_time(n)
    time_value = self["time#{n}"]
    split_time(time_value)
  end

  private

  def broadcast_replace_job
    users = User.all
    jobs  = Job.where(week_id: week.id).group_by(&:user_id)

    broadcast_replace_to(
      "weeks",
      target: "week_content_#{week.id}",
      partial: "public/jobs/public-shift",
      locals: { week: week, users: users, jobs: jobs }
    )
  end
end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < ApplicationController
  def index
    @week = Week.find(params[:week_id])
    @users = User.all
    @jobs = Job.where(week_id: @week.id).group_by(&:user_id)
    @setting = Setting.instance
  end

  def print
    @week = Week.find(params[:week_id])
    @users = User.joins(:jobs).where(jobs: { week_id: @week.id }).order('users.id ASC')
    # @users = User.where(jobs: { week_id: @week.id })
    # @users = User.all
    @jobs = Job.where(week_id: @week.id).group_by(&:user_id)
    
    render layout: "print"
  end

  def past
    @week = Week.find(params[:week_id])
    @users = User.all
    @jobs = Job.where(week_id: @week.id).group_by(&:user_id)
  end
  
end

app/helpers/admin/jobs_helper.rb
module Admin::JobsHelper
end

app/views/admin/jobs/_is-created-switch.html.erb
<% if week.is_created %>
  <%= link_to is_created_admin_week_path(week.id),
    data: {
      turbo_method: :patch,
      turbo_confirm: "シフト希望の入力が可能になります\nよろしいですか？"
    },
    class: "created-status text-success text-decoration-none" do %>
      <span class="status-dot bg-success"></span>
      <span>作成済み</span>
  <% end %>
<% else %>
  <%= link_to is_created_admin_week_path(week.id),
    data: {
      turbo_method: :patch,
      turbo_confirm: "作成済みにすると、シフト希望の受付を締め切ります。\nよろしいですか？"
    },
    class: "created-status text-secondary text-decoration-none" do %>
      <span class="status-dot bg-secondary"></span>
      <span>未作成</span>
  <% end %>
<% end %>

app/views/admin/jobs/index.html.erb
<%= turbo_stream_from "weeks" %>

<div class="d-flex align-items-center gap-3">
  <h3 class="text-accent"><%= (@week.monday).day %>日～<%= (@week.sunday).day %>日のシフト希望</h3>
  <div id="week-is_created-<%= @week.id %>">
    <%= render "admin/jobs/is-created-switch", week: @week %>
  </div>
</div>

<hr>

<div class="d-flex align-items-center justify-content-between mb-3">
  <%= link_to admin_weeks_path, class: "pink-btn-link d-inline-flex align-items-center mb-1 gap-2" do %>
    <span class="material-symbols-outlined">
      arrow_back_ios_new
    </span>
    戻る
  <% end %>

  <div class="d-flex gap-2 align-items-center justify-content-end">
    <!-- 印刷ボタン -->
    <%= link_to print_admin_week_jobs_path(@week.id), 
        class: "btn btn-primary shadow d-flex", 
        target: "_blank" do %>
      <span class="material-symbols-outlined me-1">print</span>
      印刷
    <% end %>

    <!-- 削除ボタン -->
    <%= link_to admin_week_path(@week.id), 
        data: { turbo_method: :delete, 
                turbo_confirm: "#{(@week.monday).day}日～#{(@week.sunday).day}日のシフト表を削除します。よろしいですか？\n※入力されているシフト希望がすべて削除されます" }, 
        class: "btn btn-danger shadow d-flex" do %>
      <span class="material-symbols-outlined me-1">delete</span>
      削除
    <% end %>
  </div>
</div>

<div class="table-responsive table-scroll-vertical">
  <div id="week_content_<%= @week.id %>">
    <%= render "public/jobs/public-shift", week: @week, users: @users, jobs: @jobs %>
  </div>
</div>

app/views/admin/jobs/past.html.erb
<div class="d-flex align-items-center gap-3">
  <h3 class="text-accent"><%= (@week.monday).day %>日～<%= (@week.sunday).day %>日のシフト希望</h3>
  <div id="week-is_created-<%= @week.id %>">
    <%= render "admin/jobs/is-created-switch", week: @week %>
  </div>
</div>

<hr>

<div class="d-flex align-items-center justify-content-between mb-3">
  <%= link_to admin_weeks_past_path, class: "pink-btn-link d-inline-flex align-items-center mb-3 gap-2" do %>
    <span class="material-symbols-outlined">
      arrow_back_ios_new
    </span>
    戻る
  <% end %>

  <div class="d-flex gap-2 align-items-center justify-content-end">
    <!-- 印刷ボタン -->
    <%= link_to print_admin_week_jobs_path(@week.id), 
        class: "btn btn-primary shadow d-flex", 
        target: "_blank" do %>
      <span class="material-symbols-outlined me-1">print</span>
      印刷
    <% end %>

    <!-- 削除ボタン -->
    <%= link_to admin_week_path(@week.id), 
        data: { turbo_method: :delete, 
                turbo_confirm: "#{(@week.monday).day}日～#{(@week.sunday).day}日のシフト表を削除します。よろしいですか？\n※入力されているシフト希望がすべて削除されます" }, 
        class: "btn btn-danger shadow d-flex" do %>
      <span class="material-symbols-outlined me-1">delete</span>
      削除
    <% end %>
  </div>
</div>

<div class="table-responsive table-scroll-vertical">
  <%= render "public/jobs/public-shift", week: @week, users: @users, jobs: @jobs %>
</div>

app/views/admin/jobs/print.html.erb
<table class="table table-bordered table-sm text-center align-middle">
    <colgroup>
        <col style="width: 120px; border-left: 2px solid black;">
        <col style="width: 46px;">
        <col style="width: 46px;">
        <% 7.times do %>
        <col style="width: 40%;"> <!-- 出勤 -->
        <col style="width: 20%;"> <!-- 休 -->
        <col style="width: 40%;"> <!-- 退勤 -->
        <% end %>
        <col style="width: 100px; border-right: 2px solid black;">
    </colgroup>
    <thead>
        <tr><th colspan="25" style="border-top: 2px solid black; border-bottom: 1px solid black;">シフト表</th></tr>
        <tr>
            <td colspan="2" style="text-align: left; font-size: 10pt;">売上予測（千円）</td>
            <td rowspan="2" style="font-size: 8pt; border-right: 1px solid black;">人時<br>売予<br>算　</td>
            <% 7.times do %>
            <td colspan="3" style="border-right: 1px solid black;"></td>
            <% end %>
            <td colspan="3"></td>
        </tr>
        <tr>
            <td colspan="2" style="text-align: left; font-size: 10pt;">人時数（時間）</td>
            <% 7.times do %>
            <td colspan="3" style="border-right: 1px solid black;"></td>
            <% end %>
            <td colspan="3"></td>
        </tr>
        <tr>
            <td colspan="2" style="text-align: left; vertical-align: middle; font-size: 10pt;">人時売上（円）</td>
            <td style="border-right: 1px solid black;"></td>
            <th colspan="3" class="<%= holiday_class(@week.monday) %>" style="border-right: 1px solid black;"><%= day_header(@week.monday) %> (月)</th>
            <th colspan="3" class="<%= holiday_class(@week.tuesday) %>" style="border-right: 1px solid black;"><%= day_header(@week.tuesday) %> (火)</th>
            <th colspan="3" class="<%= holiday_class(@week.wednesday) %>" style="border-right: 1px solid black;"><%= day_header(@week.wednesday) %> (水)</th>
            <th colspan="3" class="<%= holiday_class(@week.thursday) %>" style="border-right: 1px solid black;"><%= day_header(@week.thursday) %> (木)</th>
            <th colspan="3" class="<%= holiday_class(@week.friday) %>" style="border-right: 1px solid black;"><%= day_header(@week.friday) %> (金)</th>
            <th colspan="3" class="<%= holiday_class(@week.saturday) || 'text-primary' %>" style="border-right: 1px solid black;"><%= day_header(@week.saturday) %> (土)</th>
            <th colspan="3" class="text-danger" style="border-right: 1px solid black;"><%= day_header(@week.sunday) %> (日)</th>
            <th colspan="3">備考</th>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid black;">氏名</td>
            <td style="font-size: 7pt; border-bottom: 1px solid black;">ヘルプ込</td>
            <td style="font-size: 7pt; border-bottom: 1px solid black; border-right: 1px solid black;">労働時間</td>
            <% 7.times do %>
            <td scope="col" style="font-size: 10pt; border-bottom: 1px solid black;">出勤</td>
            <td scope="col" style="font-size: 10pt; border-bottom: 1px solid black;">休</td>
            <td scope="col" style="font-size: 10pt; border-bottom: 1px solid black; border-right: 1px solid black;">退勤</td>
            <% end %>
            <td colspan="3" style="border-bottom: 1px solid black;"></td>
        </tr>
    </thead>
    <tbody>
        <% @users.each do |user| %>
            <% unless user == @users.last %>
            <tr>
                <td style="border-right: 1px solid black;"><%= user.full_name %></td>
                <td ></td>
                <td style="border-right: 1px solid black;"></td>
                <% (1..7).each do |n| %>
                    <% if user.job_for(@jobs).parsed_time(n).size == 2 %>
                        <td><%= user.job_for(@jobs).parsed_time(n).first %></td>
                        <td></td>
                        <td style="border-right: 1px solid black;"><%= user.job_for(@jobs).parsed_time(n).last %></td>
                    <% else %>
                        <td colspan="3" style="border-right: 1px solid black;"><%= user.job_for(@jobs).parsed_time(n).first %></td>
                    <% end %>
                <% end %>
                <td colspan="3" style="font-size: 8pt;"><%= user.job_for(@jobs).comment %></td>
            </tr>
            <% else %>
            <tr>
                <td style="border-right: 1px solid black; border-bottom: 2px solid black;"><%= user.full_name %></td>
                <td style="border-bottom: 2px solid black;"></td>
                <td style="border-right: 1px solid black; border-bottom: 2px solid black;"></td>
                <% (1..7).each do |n| %>
                    <% if user.job_for(@jobs).parsed_time(n).size == 2 %>
                        <td style="border-bottom: 2px solid black;"><%= user.job_for(@jobs).parsed_time(n).first %></td>
                        <td style="border-bottom: 2px solid black;"></td>
                        <td style="border-bottom: 2px solid black; border-right: 1px solid black;"><%= user.job_for(@jobs).parsed_time(n).last %></td>
                    <% else %>
                        <td colspan="3" style="border-bottom: 2px solid black; border-right: 1px solid black;"><%= user.job_for(@jobs).parsed_time(n).first %></td>
                    <% end %>
                <% end %>
                <td colspan="3" style="border-bottom: 2px solid black; font-size: 8pt;"><%= user.job_for(@jobs).comment %></td>
            </tr>
            <% end %>
        <% end %>
    </tbody>
</table>