config/routes.rb
Rails.application.routes.draw do

  scope module: :public do
    # root to: "homes#top"
    get "home", to:"homes#top"
    # User routes
    resource :users, only: [:index, :new, :create, :edit, :update]
    root  to: "user_sessions#new"
    post "login"    , to: "user_sessions#create"
    delete "logout" , to: "user_sessions#destroy"
    get "mypage"    , to: "users#show"
    get "myshift"   , to: "users#myshift"
    patch "reset"   , to: "users#reset"
    # Week routes
    get 'weeks/past', to: 'weeks#past'
    resources :weeks, only: [:index] do
      # Job routes
      get 'jobs/past', to: 'jobs#past'
      resources :jobs, only: [:index, :create, :edit, :update, :destroy]
    end
  end

  devise_for :admin ,controllers: {
    sessions: "admin/sessions",
    registrations: "admin/registrations"
    
  }

  namespace :admin do
    patch 'settings/toggle_visible', to: 'settings#toggle_visible'
    resources :users, only: [:index, :show, :edit, :update]
    get 'weeks/past', to: 'weeks#past'
    resources :weeks, only: [:index, :create, :destroy] do
      member do
        patch :is_created
      end
      get 'jobs/past', to: 'jobs#past'
      resources :jobs, only: [:index] do 
        collection do
          get :print
        end
      end
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/header/_admin.html.erb
<nav class="navbar navbar-dark px-3" style="background-color: #dd5b9c;">
  <ul class="nav">
    <li class="nav-item">
      <%= link_to admin_weeks_path, class: "nav-link d-flex align-items-center gap-1 fw-semibold px-3 py-2 rounded header-link", style: "color: #d3e7f5;"  do %>
      <span class="material-symbols-outlined fs-5">calendar_month</span>
        日程一覧
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to admin_users_path, class: "nav-link d-flex align-items-center gap-1 fw-semibold px-3 py-2 rounded header-link", style: "color: #d3e7f5;"  do %>
      <span class="material-symbols-outlined fs-5">groups</span>
        従業員一覧
      <% end %>
    </li>
  </ul>
  <ul class="nav">
    <li class="nav-item">
      <%= link_to destroy_admin_session_path, data: { turbo_method: :delete }, class: "nav-link d-flex align-items-center gap-1 fw-semibold px-3 py-2 rounded header-link", style: "color: #f3abc0;" do %>
        <span class="material-symbols-outlined">logout</span>
        ログアウト
      <% end %>
    </li>
  </ul>
</nav>

app/views/layouts/header/_guest.html.erb
<nav class="navbar border-bottom shadow-sm px-3" style="background-color: #d3e7f5;">
  <ul class="nav">
    <li class="nav-item">
      <%= link_to home_path, class: "nav-link d-flex align-items-center gap-1 fw-semibold px-3 py-2 rounded header-link", style: "color: #dd5b9c;" do %>
        <span class="material-symbols-outlined">icecream</span>
        ホーム
      <% end %>
    </li>
  </ul>
</nav>

app/views/layouts/header/_user.html.erb
<nav class="navbar navbar-light border-bottom px-3" style="background-color: #d3e7f5;">
  <ul class="nav">
    <li class="nav-item">
      <%= link_to weeks_path, class: "nav-link d-flex align-items-center gap-1 fw-semibold px-3 py-2 rounded header-link", style: "color: #dd5b9c;" do %>
        <span class="material-symbols-outlined fs-5">calendar_month</span>
        日程一覧
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to mypage_path, class: "nav-link d-flex align-items-center gap-1 fw-semibold px-3 py-2 rounded header-link", style: "color: #dd5b9c;" do %>
        <span class="material-symbols-outlined fs-5">person</span>
        マイページ
      <% end %>
    </li>
  </ul>
  <ul class="nav">
    <li class="nav-item">
      <%= link_to logout_path, data: { turbo_method: :delete }, class: "nav-link d-flex align-items-center gap-1 fw-semibold px-3 py-2 rounded header-link", style: "color: #f3abc0;" do %>
        <span class="material-symbols-outlined">logout</span>
        ログアウト
      <% end %>
    </li>
  </ul>
</nav>