config/routes.rb
Rails.application.routes.draw do

  scope module: :public do
    # root to: "homes#top"
    get "home", to:"homes#top"
    # User routes
    resource :users, only: [:index, :new, :create, :edit, :update]
    root  to: "user_sessions#new"
    post "login"    , to: "user_sessions#create"
    delete "logout" , to: "user_sessions#destroy"
    get "mypage"    , to: "users#show"
    get "myshift"   , to: "users#myshift"
    patch "reset"   , to: "users#reset"
    # Week routes
    get 'weeks/past', to: 'weeks#past'
    resources :weeks, only: [:index] do
      # Job routes
      get 'jobs/past', to: 'jobs#past'
      resources :jobs, only: [:index, :create, :edit, :update, :destroy]
    end
  end

  devise_for :admin ,controllers: {
    sessions: "admin/sessions",
    registrations: "admin/registrations"
    
  }

  namespace :admin do
    patch 'settings/toggle_visible', to: 'settings#toggle_visible'
    resources :users, only: [:index, :show, :edit, :update]
    get 'weeks/past', to: 'weeks#past'
    resources :weeks, only: [:index, :create, :destroy] do
      member do
        patch :is_created
      end
      get 'jobs/past', to: 'jobs#past'
      resources :jobs, only: [:index] do 
        collection do
          get :print
        end
      end
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/week.rb
class Week < ApplicationRecord
  has_many :jobs, dependent: :destroy

  validate :monday_validate
  validates :monday,
    presence: { message: '日付を入力してください。' },
    uniqueness: { message: '既に作成済みの日程です。' }

  def monday_validate
    return if monday.blank?
    unless monday.monday?
      errors.add(:monday, '月曜日を指定してください。')
    end
  end

  def sunday
    monday + 6
  end

  def tuesday
    monday + 1
  end

  def wednesday
    monday + 2
  end

  def thursday
    monday + 3
  end

  def friday
    monday + 4
  end

  def saturday
    monday + 5
  end
end

app/controllers/admin/weeks_controller.rb
class Admin::WeeksController < ApplicationController
  def index
    @week = Week.new
    load_weeks
    load_calendar
    @admin = current_admin
    @setting = Setting.instance
    @date = @today.beginning_of_week(:monday) + 21
    if (!Time.zone.today.monday? || Time.zone.now.hour >= 9) && !@weeks.exists?(monday: @date)
      puts "＝＝＝＝＝＝＝＝＝＝自動作成: #{@date}＝＝＝＝＝＝＝＝＝＝"
      Week.create(monday: @date)
      Week.find_by(monday: @date - 14)&.update(is_created: true)
      puts "＝＝＝＝＝＝＝＝＝＝#{@date - 14}＝＝＝＝＝＝＝＝＝＝"
    end
  end

  def create
    @week = Week.new(week_params)
    if @week.save
      redirect_to admin_weeks_path, notice: "#{(@week.monday).month}月#{(@week.monday).day}日～#{(@week.sunday).month}月#{(@week.sunday).day}日の週を作成しました。"
    else
      @weeks = Week.all
      load_weeks
      load_calendar
      @admin = current_admin
      @setting = Setting.instance
      respond_to do |format|
        format.html { render :index, status: :unprocessable_entity }
        format.turbo_stream { render 'create_failed', status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @week = Week.find(params[:id])
    if @week.destroy
      redirect_to admin_weeks_path, notice: "#{(@week.monday).month}月#{(@week.monday).day}日～#{(@week.sunday).month}月#{(@week.sunday).day}日の週を削除しました。"
    else
      redirect_to admin_week_job_path(@week.id), alert: 'Failed to delete week.'
    end
  end

  def past
    past_load_weeks
    past_load_calendar
    @admin = current_admin
  end

  def is_created
    @week = Week.find(params[:id])
    @week.update!(is_created: !@week.is_created)
    # redirect_to  admin_week_jobs_past_path(@week.id)
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to request.referer }
    end
  end


  private

  def week_params
    params.require(:week).permit(:monday)
  end

  def load_weeks
    #@weeks = Week.all
    @today = Date.today
    after_tommorow = Date.today + 7
    @weeks = Week.order(monday: :asc).where("monday > ?", after_tommorow).where(is_created: false)
  end

  def past_load_weeks
    @today = Date.today
    after_tommorow = Date.today + 7
    @weeks = Week.order(monday: :asc).where("monday <= ?", after_tommorow).or(Week.where(is_created: true))
  end

  def load_calendar
    if @weeks.blank?
      # Weekデータがない場合のデフォルト動作
      today = Date.today
      @start_date = today.beginning_of_month
      @end_date   = today.end_of_month
      @calendar_rows = [] # 空配列にしておく
      return
    end

    @earliest_date = @weeks.minimum(:monday)
    latest_date   = @weeks.maximum(:monday)
    # @start_month = earliest_date.beginning_of_month
    @start_date = @today.beginning_of_month
    @end_date = latest_date.end_of_month
    # @past_start_date = latest_date.beginning_of_month

    week_by_start = @start_date.cwday # 週番号（1:月曜, 7:日曜）
    week_by_end   = @end_date.cwday
    start_day = @start_date - (week_by_start - 1)
    end_day   = @end_date - (week_by_end - 1)

    days = start_day.step(end_day, 7).to_a
    week_mondays = @weeks.index_by { |week| week.monday.to_date }
    @calendar_rows = days.map { |date| [date, week_mondays[date]] }
  end

  def past_load_calendar
    if @weeks.blank?
      # Weekデータがない場合のデフォルト動作
      today = Date.today
      @start_date = today.beginning_of_month
      @end_date   = today.end_of_month
      @calendar_rows = [] # 空配列にしておく
      return
    end

    earliest_date = @weeks.minimum(:monday)
    # latest_date   = @weeks.maximum(:monday)
    @start_date = earliest_date.beginning_of_month
    # @end_date = latest_date.end_of_month
    @end_date = @weeks.maximum(:monday)
    @past_start_date = @end_date.beginning_of_month

    week_by_start = @start_date.cwday # 週番号（1:月曜, 7:日曜）
    week_by_end   = @end_date.cwday
    start_day = @start_date - (week_by_start - 1)
    end_day   = @end_date - (week_by_end - 1)

    days = start_day.step(end_day, 7).to_a
    week_mondays = @weeks.index_by { |week| week.monday.to_date }
    @calendar_rows = days.map { |date| [date, week_mondays[date]] }
  end
end

app/helpers/admin/weeks_helper.rb
module Admin::WeeksHelper
end

app/views/admin/weeks/_form.html.erb
<%= form_with model: week, url: admin_weeks_path, class: "d-flex align-items-end gap-1" do |f| %>
  <div>
    <%= f.label :monday, "作成したい週の月曜の日付を選択", class: "form-label fw-semibold text-secondary small" %>
    <%= f.date_field :monday, class: "form-control border-primary-subtle shadow-sm", required: true %>
  </div>
  <div>
    <%= f.submit "作成", class: "btn btn-primary shadow-sm" %>
  </div>
<% end %>

app/views/admin/weeks/create_failed.turbo_stream.erb
<%= turbo_stream.replace "week_errors" do %>
  <div id="week_errors">
    <% if @week.errors.any? %>
      <div class="alert alert-danger alert-dismissible fade show mt-2" role="alert">
        <% @week.errors.full_messages.each do |message| %>
          <div><%= message %></div>
        <% end %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
  </div>
<% end %>


<%= turbo_stream.replace "week_form" do %>
  <div class="card-body" id="week_form">
    <%= render 'form', week: @week %>
  </div>
<% end %>

app/views/admin/weeks/index.html.erb
<h2 class="text-accent">
  <span class="material-symbols-outlined fs-5">calendar_month</span>
  日程一覧
</h2>

<div class="d-flex align-items-center user-info-box my-4 pt-3 ps-3 rounded">
  <p class="text-muted">ログイン中のユーザ：</p>
  <p class="fw-bold text-accent">管理者</p>
</div>

<hr>
<div id="setting-visible">
  <%= render "admin/settings/switch", setting: @setting %>
</div>
<hr>

<% if flash[:notice] %>
  <div class="alert alert-blue alert-dismissible fade show mt-3" role="alert">
    <%= flash[:notice] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<div id="week_errors">
  <% if @week.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show mt-2" role="alert">
      <% @week.errors.full_messages.each do |message| %>
        <div><%= message %></div>
      <% end %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>


<h3 class="text-accent">新規作成</h3>
<div class="card-body" id="week_form">
  <%= render "form", week: @week %>
</div>

<hr class="mb-4">

<%= link_to "過去のシフト", admin_weeks_past_path, class: "pink-btn-link" %>

<h3 class="calendar-title-line text-center">
  <span id="calendar-title"><%= @start_date.strftime('%-m月') %></span>
</h3>
<div id="calendar-container" data-controller="calendar" data-earliest-date="<%= @earliest_date.to_date %>" class="calendar-grid box theme-dark">
  <div class="calendar-grid header public-calendar">
    <div class="week-day">月</div>
    <div class="week-day">火</div>
    <div class="week-day">水</div>
    <div class="week-day">木</div>
    <div class="week-day">金</div>
    <div class="week-day text-primary">土</div>
    <div class="week-day text-danger">日</div>
  </div>
  <!-- カレンダー本体 -->
  <div class="calendar-grid body">
    <% @calendar_rows.each do |date, week| %>
        <% if week %>
        <div class="week-row public-calendar">
          <%= link_to admin_week_jobs_path(week_id: week.id), class:"week-link" do %>
            <% [:monday, :tuesday, :wednesday, :thursday, :friday, :saturday, :sunday].each do |day| %>
              <% d = week.send(day).to_date %>
              <div class=
                "date 
                <%= holiday_class(d) %>
                <%= d.month.odd? ? 'odd-month' : 'even-month' %> 
                <%= 'today' if d == @today %>"
                data-month="<%= d.month %>"
                data-date="<%= d %>"
              >
                <span class="date-label"><%= d.day %></span>
              </div>
            <% end %>
          <% end %>
        </div>
        <% elsif date.monday <= Date.today + 7 %>
        <div class="week-row-3 public-calendar">
          <% (0..6).each do |day| %>
            <% d = (date + day).to_date %>
            <div class=
              "date 
              <%= holiday_class(d) %> 
              <%= d.month.odd? ? 'odd-month' : 'even-month' %> 
              <%= 'today' if d == @today %> "
              data-month="<%= d.month %>" 
              data-date="<%= d %>"
            >
              <span class="date-label">
                <% if d.month == @start_date.month %>
                  <%= d.day %>
                <% else %>
                  <%= "#{d.month}/#{d.day}" %>
                <% end %>
              </span>
            </div>
          <% end %>
        </div>
        <% else %>
        <div class="week-row-2 public-calendar">
          <% (0..6).each do |day| %>
            <% d = (date + day).to_date %>
            <div class=
              "date 
              <%= holiday_class(d) %> 
              <%= d.month.odd? ? 'odd-month' : 'even-month' %> 
              <%= 'today' if d == @today %> "
              data-month="<%= d.month %>" 
              data-date="<%= d %>"
            >
              <span class="date-label">
                <% if d.month == @start_date.month %>
                  <%= d.day %>
                <% else %>
                  <%= "#{d.month}/#{d.day}" %>
                <% end %>
              </span>
            </div>
          <% end %>
        </div>
        <% end %>
    <% end %>
  </div>
</div>

app/views/admin/weeks/is_created.turbo_stream.erb
<%= turbo_stream.replace "week-is_created-#{@week.id}" do %>
  <div id="week-is_created-<%= @week.id %>">
    <%= render "admin/jobs/is-created-switch", week: @week %>
  </div>
<% end %>

app/views/admin/weeks/past.html.erb
<h2 class="text-accent">
  <span class="material-symbols-outlined">calendar_today</span>
  過去のシフト
</h2>

<div class="d-flex align-items-center user-info-box my-4 pt-3 ps-3 rounded">
  <p class="text-muted">ログイン中のユーザ：</p>
  <p class="fw-bold text-accent">管理者</p>
</div>


<%= link_to admin_weeks_path, class: "pink-btn-link d-inline-flex align-items-center mb-1 gap-2" do %>
  <span class="material-symbols-outlined">
    arrow_back_ios_new
  </span>
  戻る
<% end %>

<h3 class="calendar-title-line text-center">
  <span id="calendar-title"><%= @past_start_date.strftime('%-m月') %></span>
</h3>
<div id="calendar-container" data-controller="past-calendar" class="calendar-grid box theme-dark">
  <div class="calendar-grid header public-calendar">
    <div class="week-day">月</div>
    <div class="week-day">火</div>
    <div class="week-day">水</div>
    <div class="week-day">木</div>
    <div class="week-day">金</div>
    <div class="week-day text-primary">土</div>
    <div class="week-day text-danger">日</div>
  </div>
  <!-- カレンダー本体 -->
  <div class="calendar-grid body">
    <% @calendar_rows.each do |date, week| %>
        <% if week %>
        <div class="week-row-2 past-link public-calendar">
          <%= link_to admin_week_jobs_past_path(week_id: week.id), class:"week-link" do %>
            <% [:monday, :tuesday, :wednesday, :thursday, :friday, :saturday, :sunday].each do |day| %>
              <% d = week.send(day).to_date %>
              <div class=
                "date 
                <%= holiday_class(d) %>
                <%= d.month.odd? ? 'odd-month' : 'even-month' %> 
                <%= 'today' if d == @today %>"
                data-month="<%= d.month %>"
                data-date="<%= d %>"
              >
                <span class="date-label"><%= d.day %></span>
              </div>
            <% end %>
          <% end %>
        </div>
        <% elsif date.monday <= Date.today + 7 %>
        <div class="week-row-3 public-calendar">
          <% (0..6).each do |day| %>
            <% d = (date + day).to_date %>
            <div class=
              "date 
              <%= holiday_class(d) %> 
              <%= d.month.odd? ? 'odd-month' : 'even-month' %> 
              <%= 'today' if d == @today %> "
              data-month="<%= d.month %>" 
              data-date="<%= d %>"
            >
              <span class="date-label">
                <% if d.month == @start_date.month %>
                  <%= d.day %>
                <% else %>
                  <%= "#{d.month}/#{d.day}" %>
                <% end %>
              </span>
            </div>
          <% end %>
        </div>
        <% else %>
        <div class="week-row-2 public-calendar">
          <% (0..6).each do |day| %>
            <% d = (date + day).to_date %>
            <div class=
              "date 
              <%= holiday_class(d) %> 
              <%= d.month.odd? ? 'odd-month' : 'even-month' %> 
              <%= 'today' if d == @today %> "
              data-month="<%= d.month %>" 
              data-date="<%= d %>"
            >
              <span class="date-label">
                <% if d.month == @start_date.month %>
                  <%= d.day %>
                <% else %>
                  <%= "#{d.month}/#{d.day}" %>
                <% end %>
              </span>
            </div>
          <% end %>
        </div>
        <% end %>
    <% end %>
  </div>
</div>